### ISSUE TITLE
$table-of-contents$ instead of $toc$

### ISSUE THREAD

**Issue by dhanak** [tajmone/pandoc-goodies#10]
https://github.com/tajmone/pandoc-goodies/blob/f2a4d286166b308258dc5e0532d61bb0023f6830/templates/html5/github/GitHub.html5#L153

This line breaks the result if the markdown file has some yaml metadata, including "toc: true". It should read $table-of-contents$ to make it work.

**Comment by tajmone** [comment]
Thanks a lot for pointing this out @dhanak! 

The repository hasn't been updated in a long time, and it looks like some pandoc changes need to be intergrated in the project to ensure its usability today. I'll do my best to take a day off to revisit the project and ensure everything is up-to-date with current pandoc version.

**Comment by dhanak** [comment]
Wow, that was a real hotfix! Thanks for the prompt response!
